/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "equittetable.h"


void
etiquettableprog_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char *allumer_1_arg;
	int  *result_2;
	log  connecter_1_arg;
	liste_fruits  *result_3;
	saison_pays  afficher_fruits_saison_local_1_arg;
	fruit  *result_4;
	fruit  fiche_fruit_1_arg;
	liste_recettes  *result_5;
	char *afficher_recettes_1_arg;
	recette  *result_6;
	int  afficher_recette_1_arg;
	int  *result_7;
	recette  ajouter_recette_favoris_1_arg;
	int  *result_8;
	recette  retirer_recette_favoris_1_arg;
	liste_recettes  *result_9;
	char *afficher_favoris_1_arg;
	pays  *result_10;
	int  pays_1_arg;
	saison  *result_11;
	int  saison_1_arg;
	ingredient  *result_12;
	int  ingredient_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ETIQUETTABLEPROG, ETIQUETTABLEVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("Scénario\n");
	printf("----------------------------------------------\n");
	printf("1.Se connecter\n");
	printf("2.Afficher les fruits en France en Avril\n");
	printf("3.Afficher la fiche de la pomme\n");
	printf("4.Afficher la liste des recettes\n");
	printf("5.Afficher la recette de Mousse au chocolat sans oeufs\n");
	printf("6.Ajouter la recette de Mousse au chocolat sans oeufs en favoris\n");
	printf("7.Afficher la liste des recettes en favoris\n");
	printf("8.Retirer la recette de Mousse au chocolat sans oeufs des favoris\n");
	printf("----------------------------------------------\n");

	result_1 = allumer_1((void*)&allumer_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	printf("\n-----------------------1.CONNECTION-----------------------\n");
	connecter_1_arg.id = 0;
	strcpy(connecter_1_arg.pseudo,"admin");
	strcpy(connecter_1_arg.mdp,"azerty");
	for(int i = 0; i<10 ;i++){
		connecter_1_arg.id_recettes_fav[i] = -1;
	}
	connecter_1_arg.nb_id_recettes_fav = 0;
	result_2 = connecter_1(&connecter_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	if(*result_2 == 0){
		printf("Connexion établie avec succès !\n");
	}else{
		printf("Echec de la connexion !\n");
	}
	printf("\n");
	
	
	afficher_fruits_saison_local_1_arg.saison.id = 3;
	strcpy(afficher_fruits_saison_local_1_arg.saison.nom,"Avril");
	afficher_fruits_saison_local_1_arg.pays.id = 0;
	strcpy(afficher_fruits_saison_local_1_arg.pays.nom,"France");
	result_3 = afficher_fruits_saison_local_1(&afficher_fruits_saison_local_1_arg, clnt);
	if (result_3 == (liste_fruits *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	printf("-----------------------2.Fruits de %s en %s :-----------------------\n",afficher_fruits_saison_local_1_arg.pays.nom,afficher_fruits_saison_local_1_arg.saison.nom);
	for(int i = 0 ; i<result_3->nb_fruits ; i++){
		printf("  -%s\n",result_3->fruits[i].nom);
	}
	printf("\n");
	
	
	fiche_fruit_1_arg = result_3->fruits[0];
	result_4 = fiche_fruit_1(&fiche_fruit_1_arg, clnt);
	if (result_4 == (fruit *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("-----------------------3.Fiche de %s-----------------------\n",result_4->nom);
	printf("  -Saisons :\n");
	for(int i = 0 ; i<12 ; i++){
		if(result_4->id_saisons[i]!= -1){
			printf("    -%s\n",saison_1(&result_4->id_saisons[i], clnt)->nom);
		}
	}
	printf("  -Pays producteurs :\n");
	for(int i = 0 ; i<result_4->nb_id_pays ; i++){
		printf("    -%s\n",pays_1(&result_4->id_pays[i], clnt)->nom);
	}
	printf("  -Calories : %lf\n",result_4->calories);
	printf("  -Sucres : %lf\n",result_4->sucres);
	printf("  -Recettes :\n");
	for(int i = 0 ; i<result_4->nb_id_recettes ; i++){
		printf("    -%s\n",afficher_recette_1(&result_4->id_recettes[i], clnt)->nom);
	}
	printf("\n");
	
	
	result_5 = afficher_recettes_1((void*)&afficher_recettes_1_arg, clnt);
	if (result_5 == (liste_recettes *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("-----------------------4.Liste de toutes les recettes-----------------------\n");
	for(int i = 0 ; i<result_5->nb_recettes ; i++){
		printf("  -%s\n",result_5->recettes[i].nom);
	}
	printf("\n");
	
	afficher_recette_1_arg = 0;
	result_6 = afficher_recette_1(&afficher_recette_1_arg, clnt);
	if (result_6 == (recette *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	printf("-----------------------5.Recette de %s-----------------------\n",result_6->nom);
	printf("  -Temps :%d minutes\n",result_6->temps);
	printf("  -Budget :%s\n",result_6->budget);
	printf("  -Kcal / Pers :%d\n",result_6->kcal);
	printf("  -Ingrédients :\n");
	for(int i = 0; i<result_6->nb_id_ingredients ; i++){
		ingredient * ingredient_recette = ingredient_1(&result_6->id_ingredients[i], clnt);
		printf("    -%s ",ingredient_recette->nom);
		printf("%lf ",ingredient_recette->quantite);
		printf("%s\n",ingredient_recette->mesure);
	}
	printf("  -Auteur :%s\n",result_6->auteur);
	printf("\n");
	
	
	printf("-----------------------6.Ajout en Favoris-----------------------\n");
	ajouter_recette_favoris_1_arg = *result_6;
	result_7 = ajouter_recette_favoris_1(&ajouter_recette_favoris_1_arg, clnt);
	if (result_7 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	if(*result_7 == 0){
		printf("Recette ajoutée aux favoris avec succès !\n");
	}
	if(*result_7 == 1){
		printf("Aucun compte connecté !\n");
	}
	if(*result_7 == 2){
		printf("Nombre maximum de favoris déjà atteint !\n");
	}
	if(*result_7 == 3){
		printf("Recette déjà en favoris !\n");
	}
	printf("\n");
	
	
	printf("-----------------------7.Affichage des favoris-----------------------\n");
	result_9 = afficher_favoris_1((void*)&afficher_favoris_1_arg, clnt);
	if (result_9 == (liste_recettes *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	if(result_9->nb_recettes == 0){
		printf("Aucune recette en favoris !\n");
	}else{
		printf("Liste des recettes en favoris :\n");
		for(int i = 0 ; i<result_9->nb_recettes ; i++){
			printf("  -%s\n",result_9->recettes[i].nom);
		}
	}
	printf("\n");
	
	
	printf("-----------------------8.Retrait d'un favoris-----------------------\n");
	retirer_recette_favoris_1_arg = *result_6;
	result_8 = retirer_recette_favoris_1(&retirer_recette_favoris_1_arg, clnt);
	if (result_8 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	if(*result_8 == 0){
		printf("Retrait réussi !\n");
	}
	if(*result_8 == 1){
		printf("Aucun compte connecté !\n");
	}
	if(*result_8 == 2){
		printf("Cette recette n'est pas en favoris !\n");
	}
	printf("\n");
	
	
	printf("-----------------------7.Affichage des favoris-----------------------\n");
	result_9 = afficher_favoris_1((void*)&afficher_favoris_1_arg, clnt);
	if (result_9 == (liste_recettes *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	if(result_9->nb_recettes == 0){
		printf("Aucune recette en favoris !\n");
	}else{
		printf("Liste des recettes en favoris :\n");
		for(int i = 0 ; i<result_9->nb_recettes ; i++){
			printf("  -%s\n",result_9->recettes[i].nom);
		}
	}
	printf("\n");
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	etiquettableprog_1 (host);
exit (0);
}
