/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "equittetable.h"

int id_compte_connecte = -1;
liste_pays t_pays;
liste_saisons t_saisons;
liste_log t_log;
liste_ingredients t_ingredients;
liste_recettes t_recettes;
liste_fruits t_fruits;

void *
allumer_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;
	printf("Exécution de allumer_1_svc\n");
	printf("-----------------------------------\n");

	/*
	 * insert server code here
	 */
	 
	//Pays
	t_pays.liste_pays[0].id = 0;
	strcpy(t_pays.liste_pays[0].nom,"France");
	t_pays.liste_pays[1].id = 1;
	strcpy(t_pays.liste_pays[1].nom,"Pologne");
	t_pays.liste_pays[2].id = 2;
	strcpy(t_pays.liste_pays[2].nom,"Italie");
	t_pays.liste_pays[3].id = 3;
	strcpy(t_pays.liste_pays[3].nom,"Grèce");
	t_pays.liste_pays[4].id = 4;
	strcpy(t_pays.liste_pays[4].nom,"NvZélande");
	t_pays.liste_pays[5].id = 5;
	strcpy(t_pays.liste_pays[5].nom,"Danemark");
	t_pays.liste_pays[6].id = 6;
	strcpy(t_pays.liste_pays[6].nom,"Hongrie");
	t_pays.nb_liste_pays = 7;
	
	//Saisons
	t_saisons.liste_saisons[0].id = 0;
	strcpy(t_saisons.liste_saisons[0].nom,"Janvier");
	t_saisons.liste_saisons[1].id = 1;
	strcpy(t_saisons.liste_saisons[1].nom,"Février");
	t_saisons.liste_saisons[2].id = 2;
	strcpy(t_saisons.liste_saisons[2].nom,"Mars");
	t_saisons.liste_saisons[3].id = 3;
	strcpy(t_saisons.liste_saisons[3].nom,"Avril");
	t_saisons.liste_saisons[4].id = 4;
	strcpy(t_saisons.liste_saisons[4].nom,"Mai");
	t_saisons.liste_saisons[5].id = 5;
	strcpy(t_saisons.liste_saisons[5].nom,"Juin");
	t_saisons.liste_saisons[6].id = 6;
	strcpy(t_saisons.liste_saisons[6].nom,"Juillet");
	t_saisons.liste_saisons[7].id = 7;
	strcpy(t_saisons.liste_saisons[7].nom,"Août");
	t_saisons.liste_saisons[8].id = 8;
	strcpy(t_saisons.liste_saisons[8].nom,"Septembre");
	t_saisons.liste_saisons[9].id = 9;
	strcpy(t_saisons.liste_saisons[9].nom,"Octobre");
	t_saisons.liste_saisons[10].id = 10;
	strcpy(t_saisons.liste_saisons[10].nom,"Novembre");
	t_saisons.liste_saisons[11].id = 11;
	strcpy(t_saisons.liste_saisons[11].nom,"Décembre");
	t_saisons.nb_saisons = 12;
	
	//Comptes
	t_log.liste_log[0].id = 0;
	strcpy(t_log.liste_log[0].pseudo,"admin");
	strcpy(t_log.liste_log[0].mdp,"azerty");
	for(int i = 0; i<10 ;i++){
		t_log.liste_log[0].id_recettes_fav[i] = -1;
	}
	t_log.liste_log[0].nb_id_recettes_fav = 0;
	
	t_log.liste_log[1].id = 1;
	strcpy(t_log.liste_log[1].pseudo,"test");
	strcpy(t_log.liste_log[1].mdp,"b4dmdp");
	for(int i = 0; i<10 ;i++){
		t_log.liste_log[1].id_recettes_fav[i] = -1;
	}
	t_log.liste_log[1].nb_id_recettes_fav = 0;
	
	t_log.liste_log[2].id = 2;
	strcpy(t_log.liste_log[2].pseudo,"shadow");
	strcpy(t_log.liste_log[2].mdp,"qwerty");
	for(int i = 0; i<10 ;i++){
		t_log.liste_log[2].id_recettes_fav[i] = -1;
	}
	t_log.liste_log[2].nb_id_recettes_fav = 0;
	t_log.nb_liste_log = 3;
	
	//Ingredients
	t_ingredients.liste[0].id = 0;
	strcpy(t_ingredients.liste[0].nom,"tofu");
	t_ingredients.liste[0].quantite = 75.0;
	strcpy(t_ingredients.liste[0].mesure,"g");
	
	t_ingredients.liste[1].id = 1;
	strcpy(t_ingredients.liste[1].nom,"citron");
	t_ingredients.liste[1].quantite = 1.0;
	strcpy(t_ingredients.liste[1].mesure,"g(jus)");
	
	t_ingredients.liste[2].id = 2;
	strcpy(t_ingredients.liste[2].nom,"chocolat");
	t_ingredients.liste[2].quantite = 100.0;
	strcpy(t_ingredients.liste[2].mesure,"g");
	
	t_ingredients.liste[3].id = 3;
	strcpy(t_ingredients.liste[3].nom,"miel");
	t_ingredients.liste[3].quantite = 1.0;
	strcpy(t_ingredients.liste[3].mesure,"c.soupe");
	
	t_ingredients.liste[4].id = 4;
	strcpy(t_ingredients.liste[4].nom,"pomme");
	t_ingredients.liste[4].quantite = 1.0;
	strcpy(t_ingredients.liste[4].mesure,"unité(s)");
	
	t_ingredients.liste[5].id = 5;
	strcpy(t_ingredients.liste[5].nom,"groseil.");
	t_ingredients.liste[5].quantite = 20.0;
	strcpy(t_ingredients.liste[5].mesure,"g");
	
	t_ingredients.liste[6].id = 6;
	strcpy(t_ingredients.liste[6].nom,"miel");
	t_ingredients.liste[6].quantite = 2.0;
	strcpy(t_ingredients.liste[6].mesure,"c.soupe");
	t_ingredients.nb_ingredients = 7;
	
	//Recettes
	t_recettes.recettes[0].id = 0;
	strcpy(t_recettes.recettes[0].nom,"Mousse");
	strcpy(t_recettes.recettes[0].auteur,"ADEME");
	t_recettes.recettes[0].temps = 30;
	strcpy(t_recettes.recettes[0].budget,"€");
	t_recettes.recettes[0].kcal = 256;
	t_recettes.recettes[0].id_ingredients[0] = 0;
	t_recettes.recettes[0].id_ingredients[1] = 1;
	t_recettes.recettes[0].id_ingredients[2] = 2;
	t_recettes.recettes[0].id_ingredients[3] = 4;
	t_recettes.recettes[0].nb_id_ingredients = 4;
	
	t_recettes.recettes[1].id = 1;
	strcpy(t_recettes.recettes[1].nom,"Porridge");
	strcpy(t_recettes.recettes[1].auteur,"Lucie");
	t_recettes.recettes[1].temps = 10;
	strcpy(t_recettes.recettes[1].budget,"€");
	t_recettes.recettes[1].kcal = 282;
	t_recettes.recettes[1].id_ingredients[0] = 3;
	t_recettes.recettes[1].id_ingredients[1] = 4;
	t_recettes.recettes[1].nb_id_ingredients = 2;
	
	t_recettes.recettes[2].id = 2;
	strcpy(t_recettes.recettes[2].nom,"Crem ete");
	strcpy(t_recettes.recettes[2].auteur,"FNE");
	t_recettes.recettes[2].temps = 30;
	strcpy(t_recettes.recettes[2].budget,"€");
	t_recettes.recettes[2].kcal = 182;
	t_recettes.recettes[2].id_ingredients[0] = 5;
	t_recettes.recettes[2].id_ingredients[1] = 4;
	t_recettes.recettes[2].id_ingredients[2] = 0;
	t_recettes.recettes[2].id_ingredients[3] = 6;
	t_recettes.recettes[2].nb_id_ingredients = 4;
	
	t_recettes.nb_recettes = 3;
	
	//Fruits
	t_fruits.fruits[0].id = 0;
	strcpy(t_fruits.fruits[0].nom,"pomme");
	t_fruits.fruits[0].calories = 53.5;
	t_fruits.fruits[0].sucres = 11.2;
	for(int i = 0 ; i<10;i++){
		t_fruits.fruits[0].id_pays[i] = -1;
	}
	t_fruits.fruits[0].id_pays[0] = 0;
	t_fruits.fruits[0].id_pays[1] = 1;
	t_fruits.fruits[0].id_pays[2] = 2;
	t_fruits.fruits[0].nb_id_pays = 3;
	for(int i = 0 ; i<12;i++){
		t_fruits.fruits[0].id_saisons[i] = -1;
	}
	t_fruits.fruits[0].id_saisons[0] = 0;
	t_fruits.fruits[0].id_saisons[1] = 1;
	t_fruits.fruits[0].id_saisons[2] = 2;
	t_fruits.fruits[0].id_saisons[3] = 3;
	t_fruits.fruits[0].id_saisons[7] = 7;
	t_fruits.fruits[0].id_saisons[8] = 8;
	t_fruits.fruits[0].id_saisons[9] = 9;
	t_fruits.fruits[0].id_saisons[10] = 10;
	t_fruits.fruits[0].id_saisons[11] = 11;
	for(int i = 0 ; i<10;i++){
		t_fruits.fruits[0].id_recettes[i] = -1;
	}
	t_fruits.fruits[0].id_recettes[0] = 0;
	t_fruits.fruits[0].id_recettes[1] = 1;
	t_fruits.fruits[0].nb_id_recettes = 2;
	
	t_fruits.fruits[1].id = 1;
	strcpy(t_fruits.fruits[1].nom,"kiwi");
	t_fruits.fruits[1].calories = 58.5;
	t_fruits.fruits[1].sucres = 7.9;
	for(int i = 0 ; i<10;i++){
		t_fruits.fruits[1].id_pays[i] = -1;
	}
	t_fruits.fruits[1].id_pays[0] = 0;
	t_fruits.fruits[1].id_pays[1] = 2;
	t_fruits.fruits[1].id_pays[2] = 3;
	t_fruits.fruits[1].id_pays[3] = 4;
	t_fruits.fruits[1].nb_id_pays = 4;
	for(int i = 0 ; i<12;i++){
		t_fruits.fruits[1].id_saisons[i] = -1;
	}
	t_fruits.fruits[1].id_saisons[0] = 0;
	t_fruits.fruits[1].id_saisons[1] = 1;
	t_fruits.fruits[1].id_saisons[2] = 2;
	t_fruits.fruits[1].id_saisons[3] = 3;
	t_fruits.fruits[1].id_saisons[10] = 10;
	t_fruits.fruits[1].id_saisons[11] = 11;
	for(int i = 0 ; i<10;i++){
		t_fruits.fruits[1].id_recettes[i] = -1;
	}
	t_fruits.fruits[1].nb_id_recettes = 0;
	
	t_fruits.fruits[2].id = 2;
	strcpy(t_fruits.fruits[2].nom,"groseil.");
	t_fruits.fruits[2].calories = 56.1;
	t_fruits.fruits[2].sucres = 6.6;
	for(int i = 0 ; i<10;i++){
		t_fruits.fruits[2].id_pays[i] = -1;
	}
	t_fruits.fruits[2].id_pays[0] = 0;
	t_fruits.fruits[2].id_pays[1] = 1;
	t_fruits.fruits[2].id_pays[2] = 5;
	t_fruits.fruits[2].id_pays[3] = 6;
	t_fruits.fruits[2].nb_id_pays = 4;
	for(int i = 0 ; i<12;i++){
		t_fruits.fruits[2].id_saisons[i] = -1;
	}
	t_fruits.fruits[2].id_saisons[5] = 5;
	t_fruits.fruits[2].id_saisons[6] = 6;
	t_fruits.fruits[2].id_saisons[7] = 7;
	for(int i = 0 ; i<10;i++){
		t_fruits.fruits[2].id_recettes[i] = -1;
	}
	t_fruits.fruits[2].id_recettes[0] = 2;
	t_fruits.fruits[2].nb_id_recettes = 1;
	
	t_fruits.nb_fruits = 3;
	


	return (void *) &result;
}

int *
connecter_1_svc(log *argp, struct svc_req *rqstp)
{
	static int result;
	printf("Exécution de connecter_1_svc\n");
	printf("-----------------------------------\n");

	/*
	 * insert server code here
	 */
	
	for(int i = 0; i<t_log.nb_liste_log ; i++){
		if(strcmp(argp->pseudo,t_log.liste_log[i].pseudo) == 0){
			if(strcmp(argp->mdp,t_log.liste_log[i].mdp) == 0){
				id_compte_connecte = t_log.liste_log[i].id;
				result = 0;
				return &result;
			}
		}
	}
	id_compte_connecte = -1;
	result = 1;
	return &result;
}

liste_fruits *
afficher_fruits_saison_local_1_svc(saison_pays *argp, struct svc_req *rqstp)
{
	static liste_fruits  result;
	printf("Exécution de afficher_fruits_saison_local_1_svc\n");
	printf("-----------------------------------\n");

	/*
	 * insert server code here
	 */
	 
	result.nb_fruits = 0; 
	for(int i =0 ; i<t_fruits.nb_fruits ; i++){
		if(t_fruits.fruits[i].id_saisons[argp->saison.id] == argp->saison.id){
			for(int j = 0 ; j<t_fruits.fruits[i].nb_id_pays ; j++){
				if(t_fruits.fruits[i].id_pays[j] == argp->pays.id){
					result.fruits[result.nb_fruits] = t_fruits.fruits[i];
					result.nb_fruits += 1;
				}
			}
		}
	}

	return &result;
}

fruit *
fiche_fruit_1_svc(fruit *argp, struct svc_req *rqstp)
{

	/*
	 * insert server code here
	 */
	printf("Exécution de fiche_fruit_1_svc\n");
	printf("-----------------------------------\n");
	return argp;
}

liste_recettes *
afficher_recettes_1_svc(void *argp, struct svc_req *rqstp)
{
	static liste_recettes  result;
	result = t_recettes;
	printf("Exécution de afficher_recettes_1_svc\n");
	printf("-----------------------------------\n");

	/*
	 * insert server code here
	 */

	return &result;
}

recette *
afficher_recette_1_svc(int *argp, struct svc_req *rqstp)
{
	static recette  result;
	result = t_recettes.recettes[*argp];
	printf("Exécution de afficher_recette_1_svc\n");
	printf("-----------------------------------\n");

	/*
	 * insert server code here
	 */

	return &result;
}

int *
ajouter_recette_favoris_1_svc(recette *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("Exécution de ajouter_recette_favoris_1_svc\n");
	printf("-----------------------------------\n");

	/*
	 * insert server code here
	 */
	 
	if(id_compte_connecte == -1){
		result = 1;
		return & result;
	}
	if(t_log.liste_log[id_compte_connecte].nb_id_recettes_fav == 10){
		result = 2;
		return &result;
	}
	for(int i = 0 ; i<t_log.liste_log[id_compte_connecte].nb_id_recettes_fav ; i++){
		if(argp->id == t_log.liste_log[id_compte_connecte].id_recettes_fav[i]){
			result = 3;
			return &result;
		}
	}
	t_log.liste_log[id_compte_connecte].id_recettes_fav[t_log.liste_log[id_compte_connecte].nb_id_recettes_fav] = argp->id;
	t_log.liste_log[id_compte_connecte].nb_id_recettes_fav += 1;

	return &result;
}

int *
retirer_recette_favoris_1_svc(recette *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("Exécution de retirer_recette_favoris_1_svc\n");
	printf("-----------------------------------\n");

	/*
	 * insert server code here
	 */
	 
	if(id_compte_connecte == -1){
		result = 1;
		return &result;
	}
	int trouve = -1;
	for(int i = 0 ; i<t_log.liste_log[id_compte_connecte].nb_id_recettes_fav; i++){
		if(t_log.liste_log[id_compte_connecte].id_recettes_fav[i] == argp->id){
			trouve = i;
			t_log.liste_log[id_compte_connecte].id_recettes_fav[i] = -1;
		}
	}
	if(trouve == -1){
		result = 2;
		return &result;
	}
	for(int j = trouve; j<t_log.liste_log[id_compte_connecte].nb_id_recettes_fav-1 ; j++){
		t_log.liste_log[id_compte_connecte].id_recettes_fav[j] = t_log.liste_log[id_compte_connecte].id_recettes_fav[j+1];
	}
	t_log.liste_log[id_compte_connecte].nb_id_recettes_fav -= 1;
	result = 0;

	return &result;
}

liste_recettes *
afficher_favoris_1_svc(void *argp, struct svc_req *rqstp)
{
	static liste_recettes  result;
	printf("Exécution de afficher_favoris_1_svc\n");
	printf("-----------------------------------\n");

	/*
	 * insert server code here
	 */
	 
	result.nb_recettes = 0;
	if(id_compte_connecte != -1){
		for(int i = 0; i<t_log.liste_log[id_compte_connecte].nb_id_recettes_fav ; i++){
			result.recettes[result.nb_recettes] = t_recettes.recettes[t_log.liste_log[id_compte_connecte].id_recettes_fav[i]];
			result.nb_recettes += 1;
		}
		return &result;
	}

	return &result;
}

pays *
pays_1_svc(int *argp, struct svc_req *rqstp)
{
	static pays  result;
	printf("Exécution de pays_1_svc\n");
	printf("-----------------------------------\n");

	/*
	 * insert server code here
	 */

	return &t_pays.liste_pays[*argp];
}

saison *
saison_1_svc(int *argp, struct svc_req *rqstp)
{
	static saison  result;
	printf("Exécution de saison_1_svc\n");
	printf("-----------------------------------\n");

	/*
	 * insert server code here
	 */

	return &t_saisons.liste_saisons[*argp];
}

ingredient *
ingredient_1_svc(int *argp, struct svc_req *rqstp)
{
	static ingredient  result;
	printf("Exécution de ingredient_1_svc\n");
	printf("-----------------------------------\n");

	/*
	 * insert server code here
	 */

	return &t_ingredients.liste[*argp];
}
